"""update_models

Revision ID: 5eea483e9e4e
Revises: 7fb0f1bee6d2
Create Date: 2025-12-05 15:22:14.885508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eea483e9e4e'
down_revision: Union[str, None] = '7fb0f1bee6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.add_column('actions', sa.Column('interaction_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('actions_related_proposal_id_fkey'), 'actions', type_='foreignkey')
    op.drop_constraint(op.f('actions_related_interaction_id_fkey'), 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'interactions', ['interaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'actions', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'related_proposal_id')
    op.drop_column('actions', 'related_interaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('related_interaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('related_proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key(op.f('actions_related_interaction_id_fkey'), 'actions', 'interactions', ['related_interaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('actions_related_proposal_id_fkey'), 'actions', 'proposals', ['related_proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'interaction_id')
    op.drop_column('actions', 'proposal_id')
    # ### end Alembic commands ###