"""fix_typo_occurred_at

Revision ID: 7fb0f1bee6d2
Revises: b8728fcd917e
Create Date: 2025-12-04 22:18:45.491660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fb0f1bee6d2'
down_revision: Union[str, None] = 'b8728fcd917e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_occurred_at'), table_name='interactions')
    op.drop_column('interactions', 'occured_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('occured_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_interactions_occurred_at'), 'interactions', ['occurred_at'], unique=False)
    # ### end Alembic commands ###